# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: UsePythonVersion@0
       inputs:
         versionSpec: '$(pythonVersion)'
         displayName: 'Use Python $(pythonVersion)'

- script: |
    python3 -m pip install -U discord.py
    python3 bot.py
  displayName: 'Run a multi-line script'
